In [3]:
import numpy as np

In [36]:
#Creating an ARRAY
a=np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
b=np.array([10,40,50])
b

array([10, 40, 50])

In [11]:
#Creating a NumPy array with 5 values
x=np.array([5,10,15,20,25])
x

array([ 5, 10, 15, 20, 25])

In [12]:
#Creating a NumPy with 10 values
y=np.array([2,4,6,8,10,12,14,16,18,20])
y

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [34]:
#Checking the shape of X
x.shape

(5,)

In [35]:
#Checking the dimension of X
x.ndim

1

In [21]:
c=np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [33]:
#Checking the shape of C
c.shape

(2, 2)

In [32]:
#Checking the dimension of C
c.ndim

2

In [30]:
#Creating an array called D
d=np.array([[2,4],[6,8],[10,12],[14,16],[18,20]])
d

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [31]:
#Checking the dimension
d.ndim

2

In [29]:
#Checking its shape
d.shape

(5, 2)

In [28]:
#Checking the data type of D
d.dtype

dtype('int64')

In [39]:
y[2]   #Indexing

np.int64(6)

In [41]:
y[2:6] #Slicing

array([ 6,  8, 10, 12])

In [43]:
a+b    #Addition

array([11, 42, 53])

In [45]:
a-b    #Subtraction

array([ -9, -38, -47])

In [46]:
a*b    #Multiplication

array([ 10,  80, 150])

In [47]:
a/b    #Division

array([0.1 , 0.05, 0.06])

In [48]:
np.sqrt(x) #Taking square root

array([2.23606798, 3.16227766, 3.87298335, 4.47213595, 5.        ])

In [50]:
np.exp(a)  #Taking Exponential

array([ 2.71828183,  7.3890561 , 20.08553692])

In [58]:
#How exponent are calculated?
2.718**1

2.718

In [57]:
2.718**2

7.387524

In [59]:
2.718**3

20.079290231999998

In [88]:
e=np.arange(12) #Using arange function
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
e.shape    #Checking e's shape

(12,)

In [89]:
e.ndim    #Checking e's dimension

1

In [90]:
e.dtype   #Checking e's datatype

dtype('int64')

In [80]:
#Reshaping
w=e.reshape((3,4))
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
w.shape #Checking W's shape

(3, 4)

In [85]:
w.ndim #Checking W's dimension

2

In [86]:
w.dtype #Checking W's datatype

dtype('int64')